name: Demo-API-CI-2

on:
  push:
    branches:
      - main

env:
  APP_NAME: demo-api
  NAMESPACE: ghdemo
  LOGIN_SERVER: acrabc27340.azurecr.io       # Replace with your actual ACR login server
  CLUSTER_NAME: aks-abc                      # Replace with your actual AKS cluster name
  CLUSTER_RESOURCE_GROUP: aks-abc-rg         # Replace with your actual resource group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.LOGIN_SERVER }}
        username: ${{ secrets.ACR_CLIENT_ID }}
        password: ${{ secrets.ACR_CLIENT_PASSWORD }}

    - name: Build, tag, and push image to ACR
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ${{ env.LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.run_number }}

