name: Demo-API-CI-3

on:
  push:
    branches:
      - main

env:
  APP_NAME: demo-api
  NAMESPACE: ghdemo
  LOGIN_SERVER: acrabc27340.azurecr.io       # Replace with your ACR login server
  CLUSTER_NAME: aks-abc                      # Replace with your AKS cluster name
  CLUSTER_RESOURCE_GROUP: aks-abc-rg         # Replace with your resource group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.LOGIN_SERVER }}
        username: ${{ secrets.ACR_CLIENT_ID }}
        password: ${{ secrets.ACR_CLIENT_PASSWORD }}

    - name: Build, Tag & Push Docker Image to ACR
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ${{ env.LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.run_number }}


